import {
  forwardRef,
  useCallback,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from "react";
import { invoke } from "@tauri-apps/api/core";
import { convertFileSrc } from "@tauri-apps/api/core";

type Props = {
  filePath: string | null;
  startTime: number;
  endTime: number;
  removeAudio: boolean;
  probeData: {
    duration: number;
    width: number;
    height: number;
    display_width?: number;
    display_height?: number;
  } | null;
};

export type PreviewHandle = {
  startPlayback: () => void;
  stopPlayback: () => void;
  isPlaying: () => boolean;
};

// Split a concatenated JPEG byte stream into individual frame buffers.
// FFmpeg's image2pipe/mjpeg output places JPEG frames back-to-back;
// each frame begins with SOI (FF D8) and ends with EOI (FF D9).
function splitJpegStream(data: Uint8Array<ArrayBuffer>): Uint8Array<ArrayBuffer>[] {
  const frames: Uint8Array<ArrayBuffer>[] = [];
  let i = 0;
  while (i + 1 < data.length) {
    if (data[i] === 0xff && data[i + 1] === 0xd8) {
      const start = i;
      i += 2;
      while (i + 1 < data.length) {
        if (data[i] === 0xff && data[i + 1] === 0xd9) {
          frames.push(data.slice(start, i + 2) as Uint8Array<ArrayBuffer>);
          i += 2;
          break;
        }
        i += 1;
      }
    } else {
      i += 1;
    }
  }
  return frames;
}

const PreviewPane = forwardRef<PreviewHandle, Props>(function PreviewPane(
  { filePath, startTime, endTime, removeAudio, probeData },
  ref
) {
  const [frameUrl, setFrameUrl] = useState<string | null>(null);
  // WebKitGTK on Linux initialises a GStreamer audio pipeline even for muted
  // video elements. When autoaudiosink is missing the pipeline returns a NULL
  // element, a GLib-GObject-CRITICAL fires inside WebKitWebProcess, and the
  // entire renderer crashes — turning the window white. Disable live playback
  // on Linux and rely on the static frame preview (generated by ffmpeg) instead.
  // navigator.userAgent is unreliable (WebView2 can include "Linux"), so we ask
  // the backend for the actual OS.
  const [isLinux, setIsLinux] = useState(false);
  useEffect(() => {
    invoke<string>("get_os").then(os => setIsLinux(os === "linux"));
  }, []);
  useEffect(() => {
    if (videoRef.current) {
      videoRef.current.muted = removeAudio;
    }
  }, [removeAudio]);
  const [loading, setLoading] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [playing, setPlaying] = useState(false);

  // --- Filmstrip state ---
  // Blob URLs for each pre-extracted filmstrip frame. Managed manually
  // (not in React state) to avoid re-renders on every URL creation/revocation.
  const filmstripUrlsRef = useRef<string[]>([]);
  // Index into filmstripUrlsRef to display during scrubbing (null = use frameUrl)
  const [filmstripIdx, setFilmstripIdx] = useState<number | null>(null);
  const filmstripActiveRef = useRef(false); // cancels in-flight filmstrip fetch on file change

  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const activeRef = useRef(false);
  const prevStartTimeRef = useRef(startTime);
  const prevEndTimeRef = useRef(endTime);
  const prevFilePathRef = useRef<string | null>(filePath);
  const videoRef = useRef<HTMLVideoElement>(null);
  // Listener reference so we can unbind on stop. Replaces the previous 100 ms
  // setInterval polling of `currentTime`, which kept the main thread warm
  // during every playback.
  const timeUpdateHandlerRef = useRef<(() => void) | null>(null);
  const clipUrlRef = useRef<string | null>(null);
  const urlCacheRef = useRef<Map<string, string[]>>(new Map());

  const buildPlaybackUrls = useCallback((path: string): string[] => {
    // Check cache first
    if (urlCacheRef.current.has(path)) {
      return urlCacheRef.current.get(path)!;
    }

    const normalizedPath = path.replace(/\\/g, "/");
    const urls: Set<string> = new Set([convertFileSrc(path)]);

    if (normalizedPath !== path) {
      urls.add(convertFileSrc(normalizedPath));
    }

    try {
      if (/^[a-zA-Z]:\//.test(normalizedPath)) {
        urls.add(new URL(`file:///${normalizedPath}`).toString());
      } else if (normalizedPath.startsWith("/")) {
        urls.add(new URL(`file://${normalizedPath}`).toString());
      }
    } catch {
      // ignore malformed fallback URLs and continue with asset protocol URLs
    }

    const result = Array.from(urls);
    urlCacheRef.current.set(path, result);

    // Keep cache size reasonable (max 10 paths)
    if (urlCacheRef.current.size > 10) {
      const firstKey = urlCacheRef.current.keys().next().value;
      if (firstKey !== undefined) {
        urlCacheRef.current.delete(firstKey);
      }
    }

    return result;
  }, []);

  // ---------------------------------------------------------------------------
  // Filmstrip loading — fires once per file load, runs in the background
  // ---------------------------------------------------------------------------
  const clearFilmstrip = useCallback(() => {
    filmstripUrlsRef.current.forEach(u => URL.revokeObjectURL(u));
    filmstripUrlsRef.current = [];
    setFilmstripIdx(null);
  }, []);

  useEffect(() => {
    if (!filePath || !probeData || probeData.duration <= 0) {
      clearFilmstrip();
      return;
    }
    filmstripActiveRef.current = true;
    invoke<Uint8Array>("get_filmstrip", {
      path: filePath,
      durationSec: probeData.duration,
    })
      .then(rawBytes => {
        if (!filmstripActiveRef.current) return; // stale — file changed
        const frames = splitJpegStream(new Uint8Array(rawBytes.buffer as ArrayBuffer));
        if (frames.length === 0) return;
        // Revoke previous strip's URLs before replacing
        filmstripUrlsRef.current.forEach(u => URL.revokeObjectURL(u));
        filmstripUrlsRef.current = frames.map(frame => {
          const blob = new Blob([frame], { type: "image/jpeg" });
          return URL.createObjectURL(blob);
        });
      })
      .catch(() => {
        // Filmstrip is optional — scrubbing falls back to on-demand frames
      });

    return () => {
      filmstripActiveRef.current = false;
    };
  }, [filePath, probeData, clearFilmstrip]);

  // ---------------------------------------------------------------------------
  // Frame preview (static JPEG)
  // ---------------------------------------------------------------------------
  const fetchFrame = useCallback(async (path: string, time: number) => {
    activeRef.current = true;
    setLoading(true);
    try {
      const buffer = await invoke<Uint8Array>("get_preview_frame", { path, timeSec: time });
      if (activeRef.current) {
        const blob = new Blob([buffer as Uint8Array<ArrayBuffer>], { type: "image/jpeg" });
        const url = URL.createObjectURL(blob);
        setFilmstripIdx(null); // exact frame is ready — stop showing filmstrip
        setFrameUrl(prev => {
          if (prev) URL.revokeObjectURL(prev);
          return url;
        });
      }
    } catch {
      if (activeRef.current) {
        setFilmstripIdx(null);
        setFrameUrl(null);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!filePath || !probeData) {
      activeRef.current = false;
      setFrameUrl(prev => {
        if (prev) URL.revokeObjectURL(prev);
        return null;
      });
      stopPlayback();
      return;
    }
    activeRef.current = false;
    stopPlayback();
    const isNewFile = filePath !== prevFilePathRef.current;
    const isInitialRange =
      prevStartTimeRef.current === 0 &&
      prevEndTimeRef.current === 0 &&
      startTime === 0 &&
      endTime > 0;
    const startChanged = Math.abs(startTime - prevStartTimeRef.current) > 0.001;
    const endChanged = Math.abs(endTime - prevEndTimeRef.current) > 0.001;
    const frameTime =
      isNewFile || isInitialRange
        ? startTime
        : endChanged && !startChanged
          ? endTime
          : startTime;
    prevFilePathRef.current = filePath;
    prevStartTimeRef.current = startTime;
    prevEndTimeRef.current = endTime;

    // --- Show filmstrip frame immediately while debounce waits ---
    const strip = filmstripUrlsRef.current;
    if (strip.length > 0 && probeData.duration > 0) {
      const rawIdx = (frameTime / probeData.duration) * (strip.length - 1);
      const idx = Math.max(0, Math.min(Math.round(rawIdx), strip.length - 1));
      setFilmstripIdx(idx);
    }

    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(() => {
      fetchFrame(filePath, frameTime);
    }, 80); // filmstrip covers the gap; on-demand frame refines after 80 ms
    return () => {
      activeRef.current = false;
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filePath, startTime, endTime, fetchFrame, probeData]);

  // ---------------------------------------------------------------------------
  // Video playback
  // ---------------------------------------------------------------------------
  const stopPlayback = useCallback(() => {
    const vid = videoRef.current;
    if (vid && timeUpdateHandlerRef.current) {
      vid.removeEventListener("timeupdate", timeUpdateHandlerRef.current);
    }
    timeUpdateHandlerRef.current = null;
    if (vid) {
      vid.onloadedmetadata = null;
      vid.onseeked = null;
      vid.onerror = null;
      vid.pause();
      vid.src = "";
      vid.load(); // abort any in-flight load
    }
    if (clipUrlRef.current) {
      URL.revokeObjectURL(clipUrlRef.current);
      clipUrlRef.current = null;
    }
    setPlaying(false);
  }, []);

  const startPlayback = useCallback(() => {
    if (!filePath || !probeData) return;
    const vid = videoRef.current;
    if (!vid) return;
    vid.muted = removeAudio;
    const sources = buildPlaybackUrls(filePath);
    if (sources.length === 0) return;
    let sourceIndex = 0;
    let tryingGeneratedClip = false;
    let usingGeneratedClip = false;

    // Event-driven end-of-trim detection. `timeupdate` fires from the media
    // pipeline (~4 Hz per the HTML spec), so we don't need a wall-clock timer
    // waking the main thread every 100 ms. The video element's `onEnded`
    // handler (JSX prop) covers natural end-of-stream.
    const ensureStopTimer = () => {
      if (timeUpdateHandlerRef.current) {
        vid.removeEventListener("timeupdate", timeUpdateHandlerRef.current);
      }
      const handler = () => {
        if (vid.currentTime >= endTime || vid.ended) stopPlayback();
      };
      timeUpdateHandlerRef.current = handler;
      vid.addEventListener("timeupdate", handler);
    };

    const playGeneratedClip = async () => {
      if (tryingGeneratedClip) return;
      tryingGeneratedClip = true;
      try {
        const buffer = await invoke<Uint8Array>("get_preview_clip", {
          path: filePath,
          startTimeSec: startTime,
          endTimeSec: endTime,
        });
        const blob = new Blob([new Uint8Array(buffer)], { type: "video/mp4" });
        const clipUrl = URL.createObjectURL(blob);
        if (clipUrlRef.current) URL.revokeObjectURL(clipUrlRef.current);
        clipUrlRef.current = clipUrl;
        usingGeneratedClip = true;
        vid.src = clipUrl;
        await vid.play();
        setPlaying(true);
        ensureStopTimer();
      } catch {
        stopPlayback();
      }
    };

    vid.oncanplay = null;
    vid.onerror = null;
    vid.onloadedmetadata = null;
    vid.onseeked = null;

    const beginPlayback = (index: number) => {
      if (index >= sources.length) {
        stopPlayback();
        return;
      }
      sourceIndex = index;
      usingGeneratedClip = false;
      vid.src = sources[index];
      vid.play()
        .then(() => {
          setPlaying(true);
          ensureStopTimer();
        })
        .catch(() => {
          if (index + 1 < sources.length) {
            beginPlayback(index + 1);
            return;
          }
          void playGeneratedClip();
        });
    };

    vid.onerror = () => {
      if (sourceIndex + 1 < sources.length) {
        beginPlayback(sourceIndex + 1);
        return;
      }
      void playGeneratedClip();
    };

    // Seek to startTime once the browser knows the media duration, then play.
    // play() is called after the seek completes so that WebView2/Chromium does
    // not abort the pending play() when currentTime is changed mid-flight
    // (WebKit handles this gracefully; Chromium rejects the promise).
    // --autoplay-policy=no-user-gesture-required (tauri.conf.json) means the
    // async play() call is not blocked by WebView2's autoplay policy.
    vid.onloadedmetadata = () => {
      vid.onloadedmetadata = null;
      vid.currentTime = usingGeneratedClip ? 0 : startTime;
    };

    // play() must be called synchronously inside the user-gesture handler.
    // Calling it inside oncanplay (async) breaks WebView2/Chrome's autoplay
    // policy — the promise is rejected and stopPlayback() fires immediately.
    beginPlayback(0);
  }, [filePath, probeData, startTime, endTime, removeAudio, stopPlayback, buildPlaybackUrls]);

  // Expose handle so App.tsx can drive playback from keyboard shortcuts
  useImperativeHandle(ref, () => ({
    startPlayback,
    stopPlayback,
    isPlaying: () => playing,
  }), [startPlayback, stopPlayback, playing]);

  // Stop playback when trim range changes
  useEffect(() => {
    stopPlayback();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [startTime, endTime]);

  // Cleanup on unmount
  useEffect(() => () => {
    stopPlayback();
    if (debounceRef.current) clearTimeout(debounceRef.current);
    setFrameUrl(prev => {
      if (prev) URL.revokeObjectURL(prev);
      return null;
    });
    filmstripUrlsRef.current.forEach(u => URL.revokeObjectURL(u));
    filmstripUrlsRef.current = [];
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------
  const aspect = 16 / 9;
  const canPlay = !!filePath && !!probeData && endTime > startTime;

  // Filmstrip frame takes priority while the user is scrubbing; exact on-demand
  // frame replaces it once the 80 ms debounce fires and the fetch completes.
  const displayUrl =
    filmstripIdx !== null && filmstripUrlsRef.current[filmstripIdx]
      ? filmstripUrlsRef.current[filmstripIdx]
      : frameUrl;

  return (
    <div
      style={{
        background: "var(--surface)",
        border: "1px solid var(--border-subtle)",
        borderRadius: "var(--radius)",
        overflow: "hidden",
        position: "relative",
        width: "100%",
        aspectRatio: `${aspect}`,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        boxShadow: "var(--shadow-card)",
      }}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {/* Static frame preview */}
      {displayUrl && !playing ? (
        <img
          src={displayUrl}
          alt="preview"
          style={{ width: "100%", height: "100%", objectFit: "contain" }}
        />
      ) : !playing ? (
        <span style={{ color: "var(--text-disabled)", fontSize: "13px" }}>
          {loading && filmstripUrlsRef.current.length === 0
            ? "Loading preview…"
            : filePath
              ? "Preview"
              : "No file selected"}
        </span>
      ) : null}

      {/* Video element for playback */}
      <video
        ref={videoRef}
        muted={removeAudio}
        style={{
          display: playing ? "block" : "none",
          width: "100%",
          height: "100%",
          objectFit: "contain",
        }}
        onEnded={stopPlayback}
      />

      {/* Play/Stop overlay — shown on hover; disabled on Linux (GStreamer crash) */}
      {canPlay && hovered && !isLinux && (
        <div style={{
          position: "absolute",
          display: "flex",
          gap: "12px",
          alignItems: "center",
          justifyContent: "center",
        }}>
          {!playing ? (
            <button
              onClick={startPlayback}
              title="Play trim segment"
              style={overlayBtnStyle}
            >
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                <polygon points="5,3 17,10 5,17" fill="white" />
              </svg>
            </button>
          ) : (
            <button
              onClick={stopPlayback}
              title="Stop playback"
              style={overlayBtnStyle}
            >
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                <rect x="4" y="4" width="12" height="12" rx="2" fill="white" />
              </svg>
            </button>
          )}
        </div>
      )}

      {/* Info overlay */}
      {probeData && (
        <div style={{
          position: "absolute", bottom: "6px", right: "8px",
          fontSize: "11px", color: "rgba(255,255,255,0.85)",
          background: "rgba(0,0,0,0.58)", borderRadius: "var(--radius-xs)", padding: "2px 6px",
          pointerEvents: "none",
        }}>
          {probeData.width}×{probeData.height} · {probeData.duration.toFixed(1)}s
        </div>
      )}
    </div>
  );
});

export default PreviewPane;

const overlayBtnStyle: React.CSSProperties = {
  background: "rgba(0, 0, 0, 0.55)",
  border: "1px solid rgba(255, 255, 255, 0.20)",
  borderRadius: "50%",
  width: "44px",
  height: "44px",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  cursor: "pointer",
};
